config/routes.rb
Rails.application.routes.draw do
  resources :friendships
  resources :adoptions
  resources :owners
  resources :posts
  resources :cats
  root "adoptions#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/owner.rb
class Owner < ApplicationRecord
  #has_many :cats
  #has_and_belongs_to_many :cats, :uniq => true
  has_many :adoptions
  has_many :owners, :through => :adoptions
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: [:show, :edit, :update, :destroy]

  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @owner = Owner.new
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)

    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :new }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url, notice: 'Owner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_params
      params.require(:owner).permit(:name)
    end
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/owners/_form.html.slim
= form_for(@owner, html: { class: "form-horizontal", role: "form" }) do |f|
  - if @owner.errors.any?
    .alert.alert-danger.alert-dismissable role="alert"
      button.close type="button" data-dismiss="alert"
        span aria-hidden="true"
          | &times;
        span.sr-only
          | Close
      h4= "#{pluralize(@owner.errors.count,"error")} prohibited this owner from being saved:"
      ul
        - @owner.errors.full_messages.each do |msg|
          li= msg
  .form-group
    = f.label :name, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :name, class: "form-control"
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: "btn btn-primary"

app/views/owners/edit.html.slim
.page-header
  = link_to owners_path, class: 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to @owner, class: 'btn btn-primary' do
    span.glyphicon.glyphicon-info-sign
    |  Show 
  h1
    | Editing 
    | owner

= render 'form'

app/views/owners/index.html.slim
.page-header
  = link_to new_owner_path, class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-plus
    |  New Owner
  h1
    | Listing owners

.table-responsive
  table.table.table-striped.table-bordered.table-hover
    thead
      tr
        th
          | Name
        th
        th
        th
    tbody
      - @owners.each do | owner |
        tr
          td
            = owner.name
          td
            = link_to 'Show', owner
          td
            = link_to 'Edit', edit_owner_path(owner) 
          td
            = link_to 'Destroy', owner, method: :delete, data: { confirm: 'Are you sure?' } 

app/views/owners/new.html.slim
.page-header
  = link_to owners_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  h1
    | New 
    | owner

= render 'form'

app/views/owners/show.html.slim
.page-header
  = link_to owners_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to edit_owner_path(@owner), class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-pencil
    |  Edit 
  h1
    | Show owner
dl.dl-horizontal
  dt
    | Name:
  dd
    = @owner.name