config/routes.rb
Rails.application.routes.draw do
  resources :friendships
  resources :adoptions
  resources :owners
  resources :posts
  resources :cats
  root "adoptions#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/adoption.rb
class Adoption < ApplicationRecord
  belongs_to :cat
  belongs_to :owner
end

app/controllers/adoptions_controller.rb
class AdoptionsController < ApplicationController
  before_action :set_adoption, only: [:show, :edit, :update, :destroy]

  # GET /adoptions
  # GET /adoptions.json
  def index
    @adoptions = Adoption.all
  end

  # GET /adoptions/1
  # GET /adoptions/1.json
  def show
  end

  # GET /adoptions/new
  def new
    @adoption = Adoption.new
  end

  # GET /adoptions/1/edit
  def edit
  end

  # POST /adoptions
  # POST /adoptions.json
  def create
    @adoption = Adoption.new(adoption_params)

    respond_to do |format|
      if @adoption.save
        format.html { redirect_to @adoption, notice: 'Adoption was successfully created.' }
        format.json { render :show, status: :created, location: @adoption }
      else
        format.html { render :new }
        format.json { render json: @adoption.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adoptions/1
  # PATCH/PUT /adoptions/1.json
  def update
    respond_to do |format|
      if @adoption.update(adoption_params)
        format.html { redirect_to @adoption, notice: 'Adoption was successfully updated.' }
        format.json { render :show, status: :ok, location: @adoption }
      else
        format.html { render :edit }
        format.json { render json: @adoption.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adoptions/1
  # DELETE /adoptions/1.json
  def destroy
    @adoption.destroy
    respond_to do |format|
      format.html { redirect_to adoptions_url, notice: 'Adoption was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adoption
      @adoption = Adoption.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adoption_params
      params.require(:adoption).permit(:cat_id, :owner_id, :notes)
    end
end

app/helpers/adoptions_helper.rb
module AdoptionsHelper
end

app/views/adoptions/_form.html.slim
= form_for(@adoption, html: { class: "form-horizontal", role: "form" }) do |f|
  - if @adoption.errors.any?
    .alert.alert-danger.alert-dismissable role="alert"
      button.close type="button" data-dismiss="alert"
        span aria-hidden="true"
          | &times;
        span.sr-only
          | Close
      h4= "#{pluralize(@adoption.errors.count,"error")} prohibited this adoption from being saved:"
      ul
        - @adoption.errors.full_messages.each do |msg|
          li= msg
  .form-group
    = f.label :cat, class: "col-sm-2 control-label"
    .col-sm-10
      = f.collection_select :cat_id, Cat.all, :id, :name
  .form-group
    = f.label :owner, class: "col-sm-2 control-label"
    .col-sm-10
      = f.collection_select :owner_id, Owner.all, :id, :name
  .form-group
    = f.label :notes, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_area :notes, class: "form-control"
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: "btn btn-primary"

app/views/adoptions/edit.html.slim
.page-header
  = link_to adoptions_path, class: 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to @adoption, class: 'btn btn-primary' do
    span.glyphicon.glyphicon-info-sign
    |  Show 
  h1
    | Editing 
    | adoption

= render 'form'

app/views/adoptions/index.html.slim
.page-header
  = link_to new_adoption_path, class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-plus
    |  New Adoption
  h1
    | Listing adoptions

.table-responsive
  table.table.table-striped.table-bordered.table-hover
    thead
      tr
        th
          | Cat
        th
          | Owner
        th
          | Notes
        th
        th
        th
    tbody
      - @adoptions.each do | adoption |
        tr
          td
            = adoption.cat.name
          td
            = adoption.owner.name
          td
            = adoption.notes
          td
            = link_to 'Show', adoption
          td
            = link_to 'Edit', edit_adoption_path(adoption) 
          td
            = link_to 'Destroy', adoption, method: :delete, data: { confirm: 'Are you sure?' } 

app/views/adoptions/new.html.slim
.page-header
  = link_to adoptions_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  h1
    | New 
    | adoption

= render 'form'

app/views/adoptions/show.html.slim
.page-header
  = link_to adoptions_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to edit_adoption_path(@adoption), class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-pencil
    |  Edit 
  h1
    | Show adoption
dl.dl-horizontal
  dt
    | Cat:
  dd
    = @adoption.cat
  dt
    | Owner:
  dd
    = @adoption.owner
  dt
    | Notes:
  dd
    = @adoption.notes