config/routes.rb
Rails.application.routes.draw do
  resources :friendships
  resources :adoptions
  resources :owners
  resources :posts
  resources :cats
  root "adoptions#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :cat, foreign_key: :src_cat_id
  belongs_to :friend, foreign_key: :dest_cat_id, class_name: :Cat
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :set_friendship, only: [:show, :edit, :update, :destroy]

  # GET /friendships
  # GET /friendships.json
  def index
    @friendships = Friendship.all
  end

  # GET /friendships/1
  # GET /friendships/1.json
  def show
  end

  # GET /friendships/new
  def new
    @friendship = Friendship.new
  end

  # GET /friendships/1/edit
  def edit
  end

  # POST /friendships
  # POST /friendships.json
  def create
    @friendship = Friendship.new(friendship_params)

    respond_to do |format|
      if @friendship.save
        format.html { redirect_to @friendship, notice: 'Friendship was successfully created.' }
        format.json { render :show, status: :created, location: @friendship }
      else
        format.html { render :new }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friendships/1
  # PATCH/PUT /friendships/1.json
  def update
    respond_to do |format|
      if @friendship.update(friendship_params)
        format.html { redirect_to @friendship, notice: 'Friendship was successfully updated.' }
        format.json { render :show, status: :ok, location: @friendship }
      else
        format.html { render :edit }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friendships/1
  # DELETE /friendships/1.json
  def destroy
    @friendship.destroy
    respond_to do |format|
      format.html { redirect_to friendships_url, notice: 'Friendship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friendship
      @friendship = Friendship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friendship_params
      params.require(:friendship).permit(:src_cat_id, :dest_cat_id, :notes)
    end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_form.html.slim
= form_for(@friendship, html: { class: "form-horizontal", role: "form" }) do |f|
  - if @friendship.errors.any?
    .alert.alert-danger.alert-dismissable role="alert"
      button.close type="button" data-dismiss="alert"
        span aria-hidden="true"
          | &times;
        span.sr-only
          | Close
      h4= "#{pluralize(@friendship.errors.count,"error")} prohibited this friendship from being saved:"
      ul
        - @friendship.errors.full_messages.each do |msg|
          li= msg
  .form-group
    = f.label :src_cat_id, class: "col-sm-2 control-label"
    .col-sm-10
      = f.number_field :src_cat_id, class: "form-control"
  .form-group
    = f.label :dest_cat_id, class: "col-sm-2 control-label"
    .col-sm-10
      = f.number_field :dest_cat_id, class: "form-control"
  .form-group
    = f.label :notes, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_area :notes, class: "form-control"
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: "btn btn-primary"

app/views/friendships/edit.html.slim
.page-header
  = link_to friendships_path, class: 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to @friendship, class: 'btn btn-primary' do
    span.glyphicon.glyphicon-info-sign
    |  Show 
  h1
    | Editing 
    | friendship

= render 'form'

app/views/friendships/index.html.slim
.page-header
  = link_to new_friendship_path, class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-plus
    |  New Friendship
  h1
    | Listing friendships

.table-responsive
  table.table.table-striped.table-bordered.table-hover
    thead
      tr
        th
          | Src cat
        th
          | Dest cat
        th
          | Notes
        th
        th
        th
    tbody
      - @friendships.each do | friendship |
        tr
          td
            = friendship.src_cat_id
          td
            = friendship.dest_cat_id
          td
            = friendship.notes
          td
            = link_to 'Show', friendship
          td
            = link_to 'Edit', edit_friendship_path(friendship) 
          td
            = link_to 'Destroy', friendship, method: :delete, data: { confirm: 'Are you sure?' } 

app/views/friendships/new.html.slim
.page-header
  = link_to friendships_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  h1
    | New 
    | friendship

= render 'form'

app/views/friendships/show.html.slim
.page-header
  = link_to friendships_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to edit_friendship_path(@friendship), class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-pencil
    |  Edit 
  h1
    | Show friendship
dl.dl-horizontal
  dt
    | Src cat:
  dd
    = @friendship.src_cat_id
  dt
    | Dest cat:
  dd
    = @friendship.dest_cat_id
  dt
    | Notes:
  dd
    = @friendship.notes