config/routes.rb
Rails.application.routes.draw do
  resources :friendships
  resources :adoptions
  resources :owners
  resources :posts
  resources :cats
  root "adoptions#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :published)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.slim
= form_for(@post, html: { class: "form-horizontal", role: "form" }) do |f|
  - if @post.errors.any?
    .alert.alert-danger.alert-dismissable role="alert"
      button.close type="button" data-dismiss="alert"
        span aria-hidden="true"
          | &times;
        span.sr-only
          | Close
      h4= "#{pluralize(@post.errors.count,"error")} prohibited this post from being saved:"
      ul
        - @post.errors.full_messages.each do |msg|
          li= msg
  .form-group
    = f.label :title, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :title, class: "form-control"
  .form-group
    = f.label :body, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_area :body, class: "form-control"
  .form-group
    = f.label :published, class: "col-sm-2 control-label"
    .col-sm-10
      = f.check_box :published, class: "form-control"
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: "btn btn-primary"

app/views/posts/edit.html.slim
.page-header
  = link_to posts_path, class: 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to @post, class: 'btn btn-primary' do
    span.glyphicon.glyphicon-info-sign
    |  Show 
  h1
    | Editing 
    | post

= render 'form'

app/views/posts/index.html.slim
.page-header
  = link_to new_post_path, class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-plus
    |  New Post
  h1
    | Listing posts

.table-responsive
  table.table.table-striped.table-bordered.table-hover
    thead
      tr
        th
          | Title
        th
          | Body
        th
          | Published
        th
        th
        th
    tbody
      - @posts.each do | post |
        tr
          td
            = post.title
          td
            = post.body
          td
            = post.published
          td
            = link_to 'Show', post
          td
            = link_to 'Edit', edit_post_path(post) 
          td
            = link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } 

app/views/posts/new.html.slim
.page-header
  = link_to posts_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  h1
    | New 
    | post

= render 'form'

app/views/posts/show.html.slim
.page-header
  = link_to posts_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to edit_post_path(@post), class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-pencil
    |  Edit 
  h1
    | Show post
dl.dl-horizontal
  dt
    | Title:
  dd
    = @post.title
  dt
    | Body:
  dd
    = @post.body
  dt
    | Published:
  dd
    = @post.published